Description: >
  This template illustrates reference architecture for deployment on ECS.

Parameters:
  AppName:
    Type: String
    Description: The name of the sample service

  GitRepositoryName:
    Type: String
    Description: The repo name of the sample service

  GitBranchName:
    Type: String
    Description: The branch of the repo of the sample service

  TemplateBucket:
    Type: String
    Description: S3 Bucket used for nested templates

  ArtifactBucket:
    Type: String
    Description: S3 Bucket used for pipeline artifacts

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/vpc.yaml
      Parameters:
        Name: !Ref AWS::StackName
        VpcCIDR: 10.215.0.0/16
        Subnet1CIDR: 10.215.10.0/24
        Subnet2CIDR: 10.215.20.0/24

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/ecs-cluster.yaml
      Parameters:
        AppName: !Ref AppName
        VpcId: !GetAtt VPC.Outputs.VpcId
        Subnet1: !GetAtt VPC.Outputs.Subnet1
        Subnet2: !GetAtt VPC.Outputs.Subnet2
        DesiredCount: 1
        TemplateBucket: !Ref TemplateBucket
        ImageName: nginx
        ImageTag: latest

  EcrRepository:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/ecr-repository.yaml
      Parameters:
        Name: !Ref AppName

  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/deployment-pipeline.yaml
      Parameters:
        GitRepositoryName: !Ref GitRepositoryName
        GitBranchName: !Ref GitBranchName
        ImageName: !GetAtt EcrRepository.Outputs.ImageRepositoryUri
        ArtifactsBucket: !Ref ArtifactBucket
        ClusterName: !GetAtt Cluster.Outputs.ClusterName
        ServiceName: !GetAtt Cluster.Outputs.ServiceName
        ContainerName: !Ref AppName

Outputs:
  PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl

  ServiceUrl:
    Description: URL of the load balancer for the sample service.
    Value: !GetAtt Cluster.Outputs.ServiceUrl
